import {
  WeeklyDietPlan,
  WeeklyWorkoutPlan,
  AICoachInsight,
  UserPreferences,
  DailyBiometricSummary,
  DailyTrackingState,
} from '../types';

export const DEFAULT_DIET_PLAN: WeeklyDietPlan = {
  id: 'diet-plan-w1',
  generatedAt: new Date().toISOString(),
  validUntil: new Date(Date.now() + 7 * 86400000).toISOString(),
  title: 'High-Protein Lean Energy Meal Plan',
  overviewSummary: 'Engineered for fat loss with muscle preservation based on your Redmi active burn (avg 450 kcal). Focuses on nutrient-dense whole foods, quick 20-min preps, and balanced glycemic index.',
  groceryList: [
    {
      category: 'Proteins & Dairy',
      items: ['Skinless chicken breast (1.2kg)', 'Greek yogurt 0% (1kg)', 'Eggs (1 dozen)', 'Atlantic salmon fillets (400g)', 'Firm tofu / Tempeh (400g)', 'Whey/Plant protein powder'],
    },
    {
      category: 'Produce & Veggies',
      items: ['Baby spinach (2 bags)', 'Avocados (4)', 'Broccoli florets (500g)', 'Cherry tomatoes', 'Sweet potatoes (1kg)', 'Blueberries & Bananas', 'Zucchini & Bell peppers'],
    },
    {
      category: 'Grains & Pantry',
      items: ['Rolled oats', 'Quinoa', 'Brown jasmine rice', 'Extra virgin olive oil', 'Chia seeds', 'Matcha green tea powder', 'Low-sodium soy sauce / Tamari'],
    },
  ],
  days: [
    {
      dayName: 'Monday',
      targetCalories: 2050,
      totalCalories: 2040,
      totalProteinG: 148,
      totalCarbsG: 185,
      totalFatG: 62,
      dailyTip: 'Start your week with high hydration (+500ml upon waking) to boost morning metabolic rate.',
      breakfast: {
        id: 'mon-b',
        name: 'Protein Blueberry Overnight Oats',
        description: 'Rolled oats soaked in almond milk with vanilla whey, chia seeds, and fresh antioxidant blueberries.',
        calories: 480,
        proteinG: 36,
        carbsG: 58,
        fatG: 11,
        prepTimeMinutes: 5,
        ingredients: ['50g rolled oats', '1 scoop protein powder', '150ml unsweetened almond milk', '10g chia seeds', '60g fresh blueberries'],
        recipeInstructions: ['Mix oats, protein powder, chia seeds, and almond milk in a jar.', 'Refrigerate overnight.', 'Top with blueberries before eating.'],
        tags: ['High-Protein', 'Quick Prep', 'Antioxidant'],
      },
      lunch: {
        id: 'mon-l',
        name: 'Grilled Lemon Herb Chicken & Quinoa Bowl',
        description: 'Juicy chicken breast over fluffy quinoa, mixed greens, cherry tomatoes, and light tahini dressing.',
        calories: 620,
        proteinG: 48,
        carbsG: 54,
        fatG: 18,
        prepTimeMinutes: 20,
        ingredients: ['160g chicken breast', '70g dry quinoa (cooked)', '1 cup mixed salad greens', '8 cherry tomatoes', '1 tbsp tahini lemon dressing'],
        recipeInstructions: ['Season chicken with oregano, garlic, salt, and grill for 6-8 mins each side.', 'Assemble quinoa, greens, tomatoes in a bowl.', 'Slice chicken and drizzle tahini.'],
        tags: ['Lean Protein', 'Gluten-Free', 'High Fiber'],
      },
      dinner: {
        id: 'mon-d',
        name: 'Pan-Seared Salmon with Roasted Sweet Potato & Asparagus',
        description: 'Omega-3 rich salmon fillet paired with spiced sweet potato cubes and crisp asparagus.',
        calories: 650,
        proteinG: 44,
        carbsG: 48,
        fatG: 24,
        prepTimeMinutes: 22,
        ingredients: ['150g wild salmon fillet', '180g sweet potato', '100g green asparagus', '1 tsp olive oil', 'Smoked paprika & lemon'],
        recipeInstructions: ['Roast cubed sweet potatoes at 200°C for 20 mins.', 'Pan-sear salmon skin-side down for 4 mins, flip for 3 mins.', 'Sauté asparagus with garlic and olive oil.'],
        tags: ['Omega-3', 'Anti-Inflammatory', 'Heart Healthy'],
      },
      snack: {
        id: 'mon-s',
        name: 'Matcha Protein Shake & Almonds',
        description: 'Ceremonial matcha whisked with plant protein and a handful of raw almonds for sustained focus.',
        calories: 290,
        proteinG: 20,
        carbsG: 15,
        fatG: 11,
        prepTimeMinutes: 3,
        ingredients: ['1 tsp matcha powder', '1 scoop protein powder', '200ml oat milk', '15g raw almonds'],
        recipeInstructions: ['Shake matcha, protein, and oat milk with ice.', 'Enjoy alongside almonds.'],
        tags: ['Antioxidant', 'Focus', 'Low Glycemic'],
      },
    },
    {
      dayName: 'Tuesday',
      targetCalories: 2050,
      totalCalories: 2020,
      totalProteinG: 145,
      totalCarbsG: 190,
      totalFatG: 60,
      dailyTip: 'Pair carbs with complex fiber to prevent afternoon sugar crashes during desk hours.',
      breakfast: {
        id: 'tue-b',
        name: 'Scrambled Eggs with Avocado & Sourdough',
        description: '3 whole eggs scrambled with baby spinach, served with toasted sourdough and sliced ripe avocado.',
        calories: 510,
        proteinG: 28,
        carbsG: 42,
        fatG: 22,
        prepTimeMinutes: 10,
        ingredients: ['3 eggs', '1 slice sourdough', '1/2 medium avocado', 'Handful baby spinach', 'Salt & cracked black pepper'],
        recipeInstructions: ['Whisk eggs and scramble softly in a pan with spinach.', 'Toast sourdough and top with smashed avocado.', 'Plate eggs alongside.'],
        tags: ['High-Satiety', 'Healthy Fats', 'Quick Cook'],
      },
      lunch: {
        id: 'tue-l',
        name: 'Mediterranean Tuna & Chickpea Crisp Salad',
        description: 'Solid white tuna with tender chickpeas, diced cucumber, bell pepper, and parsley in olive vinaigrette.',
        calories: 580,
        proteinG: 46,
        carbsG: 48,
        fatG: 16,
        prepTimeMinutes: 12,
        ingredients: ['1 can tuna in springwater (drained)', '120g canned chickpeas', '1/2 cucumber diced', '1/2 red bell pepper', '1 tbsp extra virgin olive oil'],
        recipeInstructions: ['Combine rinsed chickpeas, tuna, cucumber, and pepper.', 'Toss with olive oil, lemon juice, salt, and sumac.'],
        tags: ['High-Protein', 'No-Cook', 'Budget Friendly'],
      },
      dinner: {
        id: 'tue-d',
        name: 'Lean Beef & Broccoli Stir-Fry over Brown Rice',
        description: 'Tender sirloin strips with vibrant broccoli, ginger, and garlic in a light savory reduction.',
        calories: 640,
        proteinG: 48,
        carbsG: 60,
        fatG: 18,
        prepTimeMinutes: 18,
        ingredients: ['150g lean beef sirloin', '150g broccoli florets', '1 cup cooked brown jasmine rice', '1 clove garlic & fresh ginger', '1 tbsp low sodium soy sauce'],
        recipeInstructions: ['Quickly sear sliced beef in a wok for 3 mins, remove.', 'Stir fry broccoli with ginger/garlic and 2 tbsp water.', 'Add beef back with soy sauce reduction and serve over rice.'],
        tags: ['Iron Rich', 'Muscle Builder', 'High Flavor'],
      },
      snack: {
        id: 'tue-s',
        name: 'Greek Yogurt with Honey & Walnuts',
        description: 'Creamy high-protein Greek yogurt with a light drizzle of raw honey and crushed walnuts.',
        calories: 290,
        proteinG: 23,
        carbsG: 20,
        fatG: 10,
        prepTimeMinutes: 2,
        ingredients: ['180g Greek yogurt 0%', '1 tsp raw honey', '15g chopped walnuts'],
        recipeInstructions: ['Scoop yogurt into a bowl and top with walnuts and honey.'],
        tags: ['Gut Health', 'Casein Protein', 'Bedtime Friendly'],
      },
    },
    {
      dayName: 'Wednesday',
      targetCalories: 2050,
      totalCalories: 2060,
      totalProteinG: 152,
      totalCarbsG: 180,
      totalFatG: 63,
      dailyTip: 'Mid-week mobility day: Keep sodium moderate and increase magnesium-rich greens.',
      breakfast: {
        id: 'wed-b',
        name: 'Super Green Protein Smoothie Bowl',
        description: 'Blended spinach, frozen banana, whey isolate, and unsweetened almond milk topped with chia.',
        calories: 460,
        proteinG: 38,
        carbsG: 52,
        fatG: 9,
        prepTimeMinutes: 5,
        ingredients: ['1 large handful spinach', '1 frozen banana', '1 scoop vanilla whey', '150ml almond milk', '10g chia seeds'],
        recipeInstructions: ['Blend all ingredients until thick and creamy.', 'Pour into bowl and sprinkle chia seeds.'],
        tags: ['Detox', 'Vitamins', 'Quick Clean'],
      },
      lunch: {
        id: 'wed-l',
        name: 'Turkey Breast & Hummus Whole Grain Wrap',
        description: 'Sliced roast turkey breast, roasted garlic hummus, shredded carrots, and crisp romaine.',
        calories: 590,
        proteinG: 45,
        carbsG: 52,
        fatG: 16,
        prepTimeMinutes: 8,
        ingredients: ['140g sliced turkey breast', '2 tbsp roasted garlic hummus', '1 large whole wheat tortilla', 'Shredded carrots & romaine lettuce'],
        recipeInstructions: ['Spread hummus evenly across tortilla.', 'Layer turkey and fresh vegetables.', 'Roll tightly and slice diagonally.'],
        tags: ['On-the-Go', 'High-Protein', 'Balanced'],
      },
      dinner: {
        id: 'wed-d',
        name: 'Crispy Baked Tofu & Sesame Soba Noodles',
        description: 'Golden pressed tofu cubes tossed with buckwheat soba, edamame, and toasted sesame ginger glaze.',
        calories: 680,
        proteinG: 44,
        carbsG: 65,
        fatG: 22,
        prepTimeMinutes: 25,
        ingredients: ['200g firm tofu (pressed)', '70g buckwheat soba noodles', '50g shelled edamame', '1 tbsp sesame oil & tamari', 'Toasted sesame seeds'],
        recipeInstructions: ['Cube tofu, toss with cornstarch, and bake/air-fry at 200°C for 18 mins until crunchy.', 'Boil soba noodles for 4 mins and rinse in cold water.', 'Toss noodles, tofu, edamame with sesame glaze.'],
        tags: ['Plant-Powered', 'Antioxidant', 'Digestive Comfort'],
      },
      snack: {
        id: 'wed-s',
        name: 'Hard Boiled Eggs & Crisp Apple Slices',
        description: '2 pasture-raised eggs with sea salt alongside crisp Honeycrisp apple slices.',
        calories: 280,
        proteinG: 15,
        carbsG: 23,
        fatG: 10,
        prepTimeMinutes: 5,
        ingredients: ['2 large eggs (boiled)', '1 medium apple', 'Sea salt & chili flakes'],
        recipeInstructions: ['Peel eggs, slice in half, season with salt and chili.', 'Serve with sliced apple.'],
        tags: ['Satiety', 'Portable', 'Whole Food'],
      },
    },
    {
      dayName: 'Thursday',
      targetCalories: 2050,
      totalCalories: 2030,
      totalProteinG: 147,
      totalCarbsG: 182,
      totalFatG: 61,
      dailyTip: 'Ensure adequate pre-workout hydration before tonight’s upper body lifting session.',
      breakfast: {
        id: 'thu-b',
        name: 'Fluffy Banana Protein Pancakes',
        description: 'Oat flour and egg white pancakes infused with ripe banana and cinnamon.',
        calories: 490,
        proteinG: 34,
        carbsG: 64,
        fatG: 9,
        prepTimeMinutes: 12,
        ingredients: ['50g oat flour', '1 scoop protein powder', '1 ripe banana', '2 egg whites', '1/2 tsp cinnamon'],
        recipeInstructions: ['Mash banana with egg whites, oat flour, and protein until smooth.', 'Cook on non-stick skillet for 2 mins per side.'],
        tags: ['High-Carb Fuel', 'Clean Treat', 'Macro-Friendly'],
      },
      lunch: {
        id: 'thu-l',
        name: 'Chimichurri Grilled Chicken Salad',
        description: 'Marinated chicken breast with fresh herb chimichurri, roasted corn, black beans, and romaine.',
        calories: 610,
        proteinG: 49,
        carbsG: 45,
        fatG: 19,
        prepTimeMinutes: 15,
        ingredients: ['160g chicken breast', '2 tbsp parsley oregano chimichurri', '60g black beans', '50g sweet corn', 'Romaine lettuce'],
        recipeInstructions: ['Grill chicken and brush with chimichurri.', 'Toss lettuce with corn and beans, top with sliced chicken.'],
        tags: ['Fresh Herbs', 'High Protein', 'Rich Flavor'],
      },
      dinner: {
        id: 'thu-d',
        name: 'Cod Fillet in Warm Tomato Caper Compote',
        description: 'Flaky white cod poached gently in garlic, sweet cherry tomatoes, capers, and olive oil with roasted potatoes.',
        calories: 620,
        proteinG: 46,
        carbsG: 46,
        fatG: 20,
        prepTimeMinutes: 22,
        ingredients: ['180g fresh cod or white fish', '150g baby potatoes', '1 cup cherry tomatoes', '1 tbsp capers', '1 tbsp olive oil'],
        recipeInstructions: ['Boil baby potatoes until tender.', 'Simmer tomatoes and capers in olive oil until bursting.', 'Nestle cod into pan and cover for 7 mins until flaky.'],
        tags: ['Lean Seafood', 'Mediterranean', 'Digestive Ease'],
      },
      snack: {
        id: 'thu-s',
        name: 'Edamame with Sea Salt & Matcha Latte',
        description: 'Steamed young soybeans in pods with flaky Maldon salt and an iced unsweetened matcha latte.',
        calories: 310,
        proteinG: 18,
        carbsG: 19,
        fatG: 13,
        prepTimeMinutes: 5,
        ingredients: ['150g edamame in pod', 'Flaky sea salt', '1 cup matcha with soy milk'],
        recipeInstructions: ['Steam edamame for 4 mins and sprinkle sea salt.', 'Whisk matcha with chilled soy milk.'],
        tags: ['Plant Protein', 'High Fiber', 'Calming'],
      },
    },
    {
      dayName: 'Friday',
      targetCalories: 2050,
      totalCalories: 2070,
      totalProteinG: 146,
      totalCarbsG: 188,
      totalFatG: 64,
      dailyTip: 'End the work week feeling energised by avoiding heavy processed oils.',
      breakfast: {
        id: 'fri-b',
        name: 'Smoked Salmon & Egg White Toast',
        description: 'Toasted whole grain rye bread topped with low-fat cottage cheese, smoked salmon, and fresh dill.',
        calories: 470,
        proteinG: 38,
        carbsG: 38,
        fatG: 14,
        prepTimeMinutes: 6,
        ingredients: ['2 slices whole grain toast', '80g smoked salmon', '60g light cottage cheese', 'Fresh dill & capers'],
        recipeInstructions: ['Spread cottage cheese over toasted bread.', 'Top with smoked salmon slices, dill, and black pepper.'],
        tags: ['Omega-3', 'High Protein', 'Gourmet'],
      },
      lunch: {
        id: 'fri-l',
        name: 'Teriyaki Chicken Rice Bowl with Zucchini',
        description: 'Tender grilled chicken glazed in homemade low-sugar teriyaki over jasmine rice with grilled zucchini ribbons.',
        calories: 650,
        proteinG: 47,
        carbsG: 65,
        fatG: 17,
        prepTimeMinutes: 18,
        ingredients: ['150g chicken thighs/breast', '1 cup cooked jasmine rice', '1 medium zucchini', '1 tbsp low-sugar teriyaki glaze', 'Sesame seeds'],
        recipeInstructions: ['Grill zucchini ribbons and chicken.', 'Glaze chicken with teriyaki in last 2 mins of cooking.', 'Serve hot over jasmine rice.'],
        tags: ['Comfort Food', 'High Energy', 'Post-Workout'],
      },
      dinner: {
        id: 'fri-d',
        name: 'Grass-Fed Steak with Garlic Butter Mushrooms & Quinoa',
        description: 'Seared lean flank steak with sautéed cremini mushrooms and fluffy seasoned quinoa.',
        calories: 660,
        proteinG: 46,
        carbsG: 46,
        fatG: 23,
        prepTimeMinutes: 20,
        ingredients: ['160g lean flank steak', '120g cremini mushrooms', '60g quinoa (cooked)', '1 tsp garlic butter', 'Rosemary'],
        recipeInstructions: ['Sear steak in cast iron skillet 3 mins per side for medium rare.', 'Sauté mushrooms in garlic butter and rosemary.', 'Rest steak 5 mins before slicing.'],
        tags: ['Zinc & Iron', 'High Satiety', 'Weekend Kickoff'],
      },
      snack: {
        id: 'fri-s',
        name: 'Dark Chocolate (85%) & Cottage Cheese Dip',
        description: 'Whipped vanilla cottage cheese with cinnamon and two squares of dark antioxidant cacao.',
        calories: 290,
        proteinG: 19,
        carbsG: 19,
        fatG: 10,
        prepTimeMinutes: 3,
        ingredients: ['150g whipped cottage cheese', '15g dark chocolate 85%', 'Pinch cinnamon & vanilla extract'],
        recipeInstructions: ['Whip cottage cheese with vanilla and cinnamon.', 'Enjoy with dark chocolate squares.'],
        tags: ['Antioxidant', 'Craving Crusher', 'Tryptophan'],
      },
    },
    {
      dayName: 'Saturday',
      targetCalories: 2150,
      totalCalories: 2120,
      totalProteinG: 148,
      totalCarbsG: 200,
      totalFatG: 65,
      dailyTip: 'Weekend active outdoor day: Replenish electrolytes after your longer outdoor walk/run.',
      breakfast: {
        id: 'sat-b',
        name: 'Loaded Shakshuka with Feta & Crusty Bread',
        description: 'Eggs gently poached in spiced tomato, bell pepper, and cumin sauce with crumbled Greek feta.',
        calories: 520,
        proteinG: 30,
        carbsG: 45,
        fatG: 22,
        prepTimeMinutes: 18,
        ingredients: ['3 eggs', '1 cup crushed San Marzano tomatoes', '1/2 bell pepper diced', '25g feta cheese', '1 slice artisan bread'],
        recipeInstructions: ['Simmer peppers, onions, tomatoes, and cumin in a pan.', 'Make 3 wells, crack eggs in, cover on low heat for 6 mins.', 'Top with feta and serve with bread.'],
        tags: ['Weekend Brunch', 'Rich Flavor', 'High Protein'],
      },
      lunch: {
        id: 'sat-l',
        name: 'Grilled Shrimp Avocado Taco Bowls',
        description: 'Spiced grilled tiger shrimp with cilantro lime brown rice, roasted peppers, and avocado crema.',
        calories: 630,
        proteinG: 44,
        carbsG: 60,
        fatG: 18,
        prepTimeMinutes: 20,
        ingredients: ['180g peeled raw shrimp', '1 cup cilantro lime brown rice', '1/2 avocado', 'Charred corn salsa', 'Lime & cumin'],
        recipeInstructions: ['Toss shrimp with chili powder, cumin, lime and sear 2 mins per side.', 'Layer rice, corn salsa, avocado, and shrimp.'],
        tags: ['Seafood', 'Fresh', 'High Protein'],
      },
      dinner: {
        id: 'sat-d',
        name: 'Herb-Roasted Chicken Breast with Crispy Potato Wedges',
        description: 'Oven-roasted bone-in or fillet chicken seasoned with thyme and rosemary beside golden air-fried potato wedges.',
        calories: 680,
        proteinG: 50,
        carbsG: 58,
        fatG: 21,
        prepTimeMinutes: 28,
        ingredients: ['180g chicken breast', '200g russet potatoes (cut into wedges)', '1 tbsp olive oil', 'Fresh rosemary & garlic powder'],
        recipeInstructions: ['Toss potato wedges in olive oil and rosemary, air fry 200°C for 22 mins.', 'Bake seasoned chicken until internal temp hits 74°C.'],
        tags: ['Family Favorite', 'High Carb Recovery', 'Wholesome'],
      },
      snack: {
        id: 'sat-s',
        name: 'Frozen Berry Protein Parfait',
        description: 'Layered Greek yogurt with crushed mixed berries and a sprinkle of toasted pumpkin seeds.',
        calories: 290,
        proteinG: 24,
        carbsG: 23,
        fatG: 9,
        prepTimeMinutes: 4,
        ingredients: ['180g Greek yogurt', '80g thawed mixed berries', '10g pumpkin seeds'],
        recipeInstructions: ['Alternate layers of yogurt and berries in a tall glass.', 'Top with crunchy pumpkin seeds.'],
        tags: ['High Zinc', 'Gut Health', 'Cooling'],
      },
    },
    {
      dayName: 'Sunday',
      targetCalories: 2050,
      totalCalories: 2010,
      totalProteinG: 144,
      totalCarbsG: 180,
      totalFatG: 59,
      dailyTip: 'Meal prep hour: Cook batch quinoa, grill chicken breasts, and portion snacks for next week.',
      breakfast: {
        id: 'sun-b',
        name: 'Cinnamon Chia Pudding with Sliced Kiwi',
        description: 'Creamy chia pudding made with unsweetened almond milk, Ceylon cinnamon, and vitamin C rich kiwi.',
        calories: 440,
        proteinG: 26,
        carbsG: 48,
        fatG: 14,
        prepTimeMinutes: 5,
        ingredients: ['25g chia seeds', '1 scoop protein powder', '180ml almond milk', '1 gold kiwi (sliced)', 'Ceylon cinnamon'],
        recipeInstructions: ['Whisk chia, protein, and milk, let set for 15 mins (or overnight).', 'Top with kiwi slices.'],
        tags: ['Digestive Health', 'Omega-3', 'Light'],
      },
      lunch: {
        id: 'sun-l',
        name: 'Asian Sesame Chicken Noodle Salad',
        description: 'Shredded poached chicken with chilled rice noodles, crunchy purple cabbage, edamame, and sesame dressing.',
        calories: 620,
        proteinG: 48,
        carbsG: 56,
        fatG: 17,
        prepTimeMinutes: 16,
        ingredients: ['150g shredded chicken breast', '60g thin rice vermicelli', '1 cup shredded red cabbage', '40g edamame', '1 tbsp toasted sesame dressing'],
        recipeInstructions: ['Cook vermicelli for 3 mins and rinse cold.', 'Toss with shredded chicken, cabbage, and sesame dressing.'],
        tags: ['Crunchy', 'High Volume', 'Cool Prep'],
      },
      dinner: {
        id: 'sun-d',
        name: 'Baked Lemon Garlic Salmon & Asparagus Foil Pack',
        description: 'Salmon baked inside parchment foil with asparagus, lemon wheels, garlic butter, and brown rice.',
        calories: 660,
        proteinG: 47,
        carbsG: 48,
        fatG: 23,
        prepTimeMinutes: 20,
        ingredients: ['160g salmon fillet', '100g asparagus spears', '1 cup brown rice (cooked)', '1 tsp garlic butter & lemon slices'],
        recipeInstructions: ['Place salmon and asparagus on foil with butter and lemon.', 'Seal pouch and bake at 200°C for 14 mins.', 'Serve alongside brown rice.'],
        tags: ['Zero Cleanup', 'Heart Healthy', 'Relaxing Prep'],
      },
      snack: {
        id: 'sun-s',
        name: 'Warm Turmeric Golden Protein Milk',
        description: 'Soothing warm oat milk with turmeric, ginger, black pepper, and gentle casein/whey protein.',
        calories: 280,
        proteinG: 23,
        carbsG: 18,
        fatG: 8,
        prepTimeMinutes: 4,
        ingredients: ['200ml warm oat milk', '1 scoop vanilla protein', '1/2 tsp turmeric & pinch black pepper', '1/4 tsp ginger'],
        recipeInstructions: ['Warm milk gently and whisk in protein, turmeric, and spices.'],
        tags: ['Anti-Inflammatory', 'Deep Sleep', 'Recovery'],
      },
    },
  ],
};

export const DEFAULT_WORKOUT_PLAN: WeeklyWorkoutPlan = {
  id: 'workout-plan-w1',
  generatedAt: new Date().toISOString(),
  title: 'Lean Strength & Redmi Adaptive Biometric Routine',
  summary: 'A 7-day periodized schedule balancing push/pull hypertrophy, lower body power, and Zone 2 heart rate mobility adapted to your Redmi Watch recovery metrics.',
  days: [
    {
      dayName: 'Monday',
      focusArea: 'Upper Body Push & Core Power',
      isRestDay: false,
      warmupMinutes: 6,
      workoutDurationMinutes: 45,
      cooldownMinutes: 5,
      estimatedBurnCalories: 380,
      intensityLevel: 'High',
      recoveryTip: 'Redmi readiness is high (>80). Great day to push for progressive overload on chest presses.',
      exercises: [
        { id: 'm1', name: 'Dumbbell Incline Chest Press', sets: 4, reps: '8-10', restSeconds: 90, targetMuscle: 'Upper Chest, Anterior Delts', equipment: 'Dumbbells & Bench', caloriesBurnEstimate: 110 },
        { id: 'm2', name: 'Overhead Dumbbell Shoulder Press', sets: 3, reps: '10-12', restSeconds: 75, targetMuscle: 'Shoulders, Triceps', equipment: 'Dumbbells', caloriesBurnEstimate: 85 },
        { id: 'm3', name: 'Parallel Bar / Bench Dips', sets: 3, reps: '12-15', restSeconds: 60, targetMuscle: 'Triceps, Lower Chest', equipment: 'Bodyweight / Parallel Bars', caloriesBurnEstimate: 70 },
        { id: 'm4', name: 'Lateral Dumbbell Raises', sets: 4, reps: '12-15', restSeconds: 45, targetMuscle: 'Lateral Deltoids', equipment: 'Dumbbells', caloriesBurnEstimate: 55 },
        { id: 'm5', name: 'Hanging Knee / Leg Raises', sets: 3, reps: '15', restSeconds: 45, targetMuscle: 'Lower Abs & Hip Flexors', equipment: 'Pull-up Bar', caloriesBurnEstimate: 60 },
      ],
    },
    {
      dayName: 'Tuesday',
      focusArea: 'Lower Body Strength & Posterior Chain',
      isRestDay: false,
      warmupMinutes: 8,
      workoutDurationMinutes: 48,
      cooldownMinutes: 6,
      estimatedBurnCalories: 430,
      intensityLevel: 'High',
      recoveryTip: 'Watch for heart rate spikes above 160 BPM; ensure full 90-120s rest between heavy squat sets.',
      exercises: [
        { id: 't1', name: 'Goblet / Barbell Back Squats', sets: 4, reps: '8-10', restSeconds: 120, targetMuscle: 'Quadriceps, Glutes', equipment: 'Barbell or Dumbbell', caloriesBurnEstimate: 140 },
        { id: 't2', name: 'Romanian Deadlifts (RDL)', sets: 4, reps: '10', restSeconds: 90, targetMuscle: 'Hamstrings, Glutes, Lower Back', equipment: 'Dumbbells or Barbell', caloriesBurnEstimate: 120 },
        { id: 't3', name: 'Walking Dumbbell Lunges', sets: 3, reps: '12 per leg', restSeconds: 60, targetMuscle: 'Glutes, Quads', equipment: 'Dumbbells', caloriesBurnEstimate: 95 },
        { id: 't4', name: 'Standing Calf Raises', sets: 4, reps: '15-20', restSeconds: 45, targetMuscle: 'Calves (Gastrocnemius)', equipment: 'Step & Dumbbell', caloriesBurnEstimate: 45 },
        { id: 't5', name: 'Plank with Shoulder Taps', sets: 3, reps: '45s', restSeconds: 45, targetMuscle: 'Core & Anti-Rotation', equipment: 'Mat', caloriesBurnEstimate: 30 },
      ],
    },
    {
      dayName: 'Wednesday',
      focusArea: 'Redmi Zone 2 Cardio & Full Body Mobility',
      isRestDay: false,
      warmupMinutes: 5,
      workoutDurationMinutes: 38,
      cooldownMinutes: 8,
      estimatedBurnCalories: 290,
      intensityLevel: 'Moderate',
      recoveryTip: 'Maintain heart rate within Zone 2 (115-135 BPM) on your Redmi watch for optimal mitochondrial health.',
      exercises: [
        { id: 'w1', name: 'Incline Treadmill Walk / Outdoor Brisk Stride', sets: 1, reps: '25 mins', restSeconds: 0, targetMuscle: 'Cardiovascular Endurance', equipment: 'Treadmill or Outdoors', caloriesBurnEstimate: 180 },
        { id: 'w2', name: 'World’s Greatest Stretch Sequence', sets: 2, reps: '6 per side', restSeconds: 30, targetMuscle: 'Hip Flexors, Thoracic Spine, Hamstrings', equipment: 'Bodyweight', caloriesBurnEstimate: 35 },
        { id: 'w3', name: 'Pigeon Pose to Cat-Cow Flow', sets: 3, reps: '60s hold', restSeconds: 30, targetMuscle: 'Gluteus Medius, Spine', equipment: 'Yoga Mat', caloriesBurnEstimate: 30 },
        { id: 'w4', name: 'Band Pull-Aparts & Dislocates', sets: 3, reps: '15', restSeconds: 30, targetMuscle: 'Rotator Cuff & Posture', equipment: 'Resistance Band', caloriesBurnEstimate: 25 },
        { id: 'w5', name: 'Deep Diaphragmatic Breathwork', sets: 1, reps: '5 mins', restSeconds: 0, targetMuscle: 'Vagus Nerve & Stress Lowering', equipment: 'Floor', caloriesBurnEstimate: 20 },
      ],
    },
    {
      dayName: 'Thursday',
      focusArea: 'Upper Body Pull & Biceps / Rear Delts',
      isRestDay: false,
      warmupMinutes: 6,
      workoutDurationMinutes: 44,
      cooldownMinutes: 5,
      estimatedBurnCalories: 370,
      intensityLevel: 'High',
      recoveryTip: 'Check your stress score before lifting: high grip strength exercises will feel smoother today.',
      exercises: [
        { id: 'th1', name: 'Lat Pulldowns or Neutral Grip Pull-Ups', sets: 4, reps: '8-10', restSeconds: 90, targetMuscle: 'Latissimus Dorsi, Biceps', equipment: 'Cable machine or Bar', caloriesBurnEstimate: 110 },
        { id: 'th2', name: 'Single-Arm Dumbbell Rows', sets: 4, reps: '10 per arm', restSeconds: 75, targetMuscle: 'Rhomboids, Mid-Back', equipment: 'Dumbbell & Bench', caloriesBurnEstimate: 95 },
        { id: 'th3', name: 'Face Pulls with Rope Cable', sets: 3, reps: '15', restSeconds: 45, targetMuscle: 'Rear Delts, External Rotators', equipment: 'Cable Machine', caloriesBurnEstimate: 55 },
        { id: 'th4', name: 'Incline Dumbbell Bicep Curls', sets: 3, reps: '10-12', restSeconds: 60, targetMuscle: 'Biceps Long Head', equipment: 'Dumbbells & Bench', caloriesBurnEstimate: 60 },
        { id: 'th5', name: 'Dead Bug Core Holds', sets: 3, reps: '12 per side', restSeconds: 45, targetMuscle: 'Deep Transverse Abdominis', equipment: 'Mat', caloriesBurnEstimate: 50 },
      ],
    },
    {
      dayName: 'Friday',
      focusArea: 'HIIT Conditioning & Functional Core',
      isRestDay: false,
      warmupMinutes: 6,
      workoutDurationMinutes: 35,
      cooldownMinutes: 6,
      estimatedBurnCalories: 360,
      intensityLevel: 'High',
      recoveryTip: 'Interval training triggers peak calorie afterburn. Watch peak heart rate on your Redmi watch.',
      exercises: [
        { id: 'f1', name: 'Kettlebell Swings (Hip Hinge)', sets: 4, reps: '15', restSeconds: 45, targetMuscle: 'Glutes, Hamstrings, Core', equipment: 'Kettlebell 16-24kg', caloriesBurnEstimate: 90 },
        { id: 'f2', name: 'Dumbbell Thrusters (Squat to Press)', sets: 3, reps: '10', restSeconds: 60, targetMuscle: 'Full Body, Quads, Shoulders', equipment: 'Light Dumbbells', caloriesBurnEstimate: 85 },
        { id: 'f3', name: 'Box Jumps or Step-Up Drives', sets: 3, reps: '12', restSeconds: 45, targetMuscle: 'Calves, Quads, Explosiveness', equipment: 'Plyo Box / Bench', caloriesBurnEstimate: 70 },
        { id: 'f4', name: 'Battle Ropes or Shadow Sprints', sets: 4, reps: '30s on / 30s off', restSeconds: 30, targetMuscle: 'Cardio, Grip, Shoulders', equipment: 'Ropes or Open Space', caloriesBurnEstimate: 75 },
        { id: 'f5', name: 'Russian Twists with Weight', sets: 3, reps: '20 total', restSeconds: 45, targetMuscle: 'Obliques', equipment: 'Dumbbell or Plate', caloriesBurnEstimate: 40 },
      ],
    },
    {
      dayName: 'Saturday',
      focusArea: 'Outdoor Nature Mobility & Active Exploration',
      isRestDay: false,
      warmupMinutes: 5,
      workoutDurationMinutes: 60,
      cooldownMinutes: 5,
      estimatedBurnCalories: 410,
      intensityLevel: 'Moderate',
      recoveryTip: 'Target 8,000 to 12,000 steps on your Redmi Watch today while enjoying outdoor fresh air.',
      exercises: [
        { id: 's1', name: 'Outdoor Trail Walk, Jog, or Park Trek', sets: 1, reps: '45-60 mins', restSeconds: 0, targetMuscle: 'Cardiovascular & Mental Reset', equipment: 'Outdoor Trail / Running Shoes', caloriesBurnEstimate: 320 },
        { id: 's2', name: 'Bodyweight Walking Lunges & High Knees', sets: 2, reps: '20 steps', restSeconds: 30, targetMuscle: 'Dynamic Mobility', equipment: 'Bodyweight', caloriesBurnEstimate: 50 },
        { id: 's3', name: 'Standing Quad & IT-Band Stretches', sets: 2, reps: '45s each', restSeconds: 0, targetMuscle: 'Quads & Hips', equipment: 'Bodyweight', caloriesBurnEstimate: 20 },
        { id: 's4', name: 'Sun Salutation Flow', sets: 3, reps: '3 rounds', restSeconds: 30, targetMuscle: 'Total Body Flow', equipment: 'Mat or Grass', caloriesBurnEstimate: 20 },
      ],
    },
    {
      dayName: 'Sunday',
      focusArea: 'Full Rest, Hydro-Recovery & Stress Reset',
      isRestDay: true,
      warmupMinutes: 0,
      workoutDurationMinutes: 20,
      cooldownMinutes: 0,
      estimatedBurnCalories: 110,
      intensityLevel: 'Recovery',
      recoveryTip: 'Rest day! Your Redmi stress score should remain below 30. Foam roll and take a warm Epsom salt bath.',
      exercises: [
        { id: 'su1', name: 'Full Body Foam Rolling (Quads, Lats, Calves)', sets: 1, reps: '10 mins', restSeconds: 0, targetMuscle: 'Myofascial Release', equipment: 'Foam Roller', caloriesBurnEstimate: 40 },
        { id: 'su2', name: 'Gentle 20-min Leisure Neighborhood Stroll', sets: 1, reps: '20 mins', restSeconds: 0, targetMuscle: 'Low Impact Mobility', equipment: 'Comfortable Footwear', caloriesBurnEstimate: 50 },
        { id: 'su3', name: '4-7-8 Parasympathetic Breathing', sets: 3, reps: '4 cycles', restSeconds: 30, targetMuscle: 'Autonomic Nervous System', equipment: 'Quiet Room', caloriesBurnEstimate: 20 },
      ],
    },
  ],
};

export const DEFAULT_AI_COACH_INSIGHT: AICoachInsight = {
  id: 'insight-1',
  generatedAt: new Date().toISOString(),
  overallStatus: 'good',
  headline: 'Solid Biometric Recovery & Balanced Caloric Deficit',
  summary: 'Your Redmi Watch shows a resting HR of 56 BPM with an optimal readiness score of 88/100. Stress levels peaked mildly at 15:00 during meetings but recovered swiftly in the evening.',
  nutritionAdvice: 'You are on track with protein intake (148g / 145g target). Keep evening complex carbs light (sweet potato/quinoa) to optimize sleep HRV recovery.',
  workoutAdjustment: 'Readiness supports today’s planned routine. Keep your main lifting sets intense with 90s rests, and monitor your watch heart rate in the 130-155 zone.',
  stressMitigationTip: 'Mid-afternoon stress reached 52. Take a 3-minute box breathing break around 14:30 tomorrow to blunt the cortisol spike before it affects appetite.',
  hydrationAlert: 'You logged 2,250ml out of 2,800ml. Add one 500ml glass before 20:00 to support glycogen replenishment and muscle recovery.',
  readinessScore: 88,
};

export const DEFAULT_PREFERENCES: UserPreferences = {
  name: 'Alex',
  age: 28,
  gender: 'male',
  heightCm: 178,
  weightKg: 75.5,
  targetWeightKg: 72,
  activityLevel: 'moderately_active',
  dietaryGoal: 'weight_loss',
  dietType: 'high_protein',
  availableEquipment: ['Bodyweight / Floor Mat', 'Resistance Bands', 'Dumbbells'],
  equipmentType: 'dumbbells',
  allergies: [],
  dislikedFoods: [],
  customInstructions: 'Quick healthy meals under 20 mins, high protein, balance carbs',
  targetCalories: 2050,
  targetProteinG: 145,
  targetCarbsG: 180,
  targetFatG: 60,
  targetWaterMl: 2800,
  targetSteps: 10000,
  autoWeeklyRefreshDay: 1, // Monday
  watchModel: 'Redmi Watch 4',
  watchConnected: true,
  watchSyncMethod: 'bluetooth_sim',
};

export const DEFAULT_DAILY_TRACKING: DailyTrackingState = {
  date: new Date().toISOString().split('T')[0],
  foodLogs: [
    {
      id: 'f-init-1',
      timestamp: '08:15',
      mealType: 'breakfast',
      name: 'Protein Blueberry Overnight Oats',
      calories: 480,
      proteinG: 36,
      carbsG: 58,
      fatG: 11,
      portion: '1 bowl (300g)',
      source: 'diet_plan',
    },
    {
      id: 'f-init-2',
      timestamp: '12:45',
      mealType: 'lunch',
      name: 'Grilled Lemon Herb Chicken & Quinoa Bowl',
      calories: 620,
      proteinG: 48,
      carbsG: 54,
      fatG: 18,
      portion: '1 plate (450g)',
      source: 'diet_plan',
    },
  ],
  waterLogs: [
    { id: 'w-1', timestamp: '08:00', amountMl: 500 },
    { id: 'w-2', timestamp: '11:30', amountMl: 500 },
    { id: 'w-3', timestamp: '14:00', amountMl: 500 },
    { id: 'w-4', timestamp: '16:30', amountMl: 500 },
  ],
  totalCalories: 1100,
  totalProteinG: 84,
  totalCarbsG: 112,
  totalFatG: 29,
  totalWaterMl: 2000,
};

export function generateSimulatedRedmiData(): DailyBiometricSummary {
  const currentHour = new Date().getHours();
  const hourlyReadings = [];

  for (let h = 0; h <= currentHour; h++) {
    const isSleeping = h >= 0 && h <= 6;
    const isMorningWorkout = h === 7 || h === 8;
    const isAfternoonStress = h === 14 || h === 15;

    let hr = 58 + Math.floor(Math.random() * 8);
    let stress = 22 + Math.floor(Math.random() * 15);
    let state: 'resting' | 'standing' | 'walking' | 'running' | 'workout' | 'sleeping' = 'resting';
    let steps = Math.floor(Math.random() * 120);

    if (isSleeping) {
      hr = 52 + Math.floor(Math.random() * 5);
      stress = 10 + Math.floor(Math.random() * 8);
      state = 'sleeping';
      steps = 0;
    } else if (isMorningWorkout) {
      hr = 125 + Math.floor(Math.random() * 30);
      stress = 40 + Math.floor(Math.random() * 15);
      state = 'workout';
      steps = 1800 + Math.floor(Math.random() * 600);
    } else if (isAfternoonStress) {
      hr = 78 + Math.floor(Math.random() * 10);
      stress = 55 + Math.floor(Math.random() * 18);
      state = 'standing';
      steps = 200 + Math.floor(Math.random() * 200);
    }

    hourlyReadings.push({
      timestamp: `${h.toString().padStart(2, '0')}:00`,
      heartRateBpm: hr,
      stressScore: stress,
      stressLevel: (stress > 65 ? 'high' : stress > 45 ? 'moderate' : stress > 25 ? 'mild' : 'relaxed') as any,
      activityState: state,
      stepIncrement: steps,
    });
  }

  const totalSteps = hourlyReadings.reduce((sum, r) => sum + r.stepIncrement, 0) + 4200;
  const activeCalories = Math.round(totalSteps * 0.042) + 210;

  return {
    date: new Date().toISOString().split('T')[0],
    restingHeartRate: 56,
    avgHeartRate: 68,
    maxHeartRate: 154,
    minHeartRate: 49,
    avgStressScore: 34,
    stressPeakTime: '14:30',
    totalSteps: Math.min(18000, totalSteps),
    totalDistanceKm: +(totalSteps * 0.00078).toFixed(2),
    activeCaloriesBurned: activeCalories,
    standingHours: Math.min(12, Math.max(4, currentHour - 2)),
    activeMinutes: 48,
    readinessScore: 88,
    sleepHours: 7.6,
    sleepQuality: 'optimal',
    hourlyReadings,
  };
}

export function shouldRefreshWeekly(refreshDayIndex: number = 1): boolean {
  try {
    const lastTimestamp = localStorage.getItem('vitalipulse_last_weekly_refresh');
    if (!lastTimestamp) return false;
    const lastDate = new Date(lastTimestamp);
    const now = new Date();
    const daysDiff = (now.getTime() - lastDate.getTime()) / (1000 * 3600 * 24);
    return daysDiff >= 7 && now.getDay() === refreshDayIndex;
  } catch {
    return false;
  }
}

export function updateWeeklyRefreshTimestamp() {
  try {
    localStorage.setItem('vitalipulse_last_weekly_refresh', new Date().toISOString());
  } catch (e) {
    console.warn('Could not save refresh timestamp:', e);
  }
}

